name: Rails CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Build the stack
        run: docker compose build

      - name: Create test database
        run: docker compose run --rm -T -e "RAILS_ENV=test" backend rails db:create

      - name: Load database schema
        run: docker compose run --rm -T -e "RAILS_ENV=test" backend rails db:schema:load
      
      - name: Run RSpec tests
        run: docker compose run --rm -T -e "RAILS_ENV=test" backend rspec
